# Generated by Django 3.2.13 on 2022-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0002_auto_20220504_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
