# Generated by Django 3.2.13 on 2022-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0006_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(choices=[('J', 'Ja'), ('JA', 'Ja, aber'), ('N', 'Nein')], max_length=1000)),
            ],
        ),
    ]
