# Generated by Django 3.2.13 on 2022-05-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0007_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Encuesta',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='question',
            new_name='pregunta',
        ),
        migrations.AddField(
            model_name='choice',
            name='encuesta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls_cms_integration.encuesta'),
        ),
    ]
