# Generated by Django 3.2.13 on 2022-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0009_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('J', 'Ja'), ('JAB', 'Ja, aber'), ('N', 'Nein')], default='J', max_length=1000),
        ),
    ]
