# Generated by Django 3.2.13 on 2022-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0011_alter_choice_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Ja, aber', 'Ja, aber'), ('Nein', 'Nein')], default='Ja', max_length=1000),
        ),
    ]
