# Generated by Django 3.2.13 on 2022-06-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0012_alter_choice_choice_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
