# Generated by Django 3.2.13 on 2022-06-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0013_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(choices=[('Ja', 'Ja'), ('Ja, aber', 'Ja, aber'), ('Nein', 'Nein')], default='Ja', max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_cms_integration.encuesta')),
            ],
        ),
    ]
