# Generated by Django 3.2.13 on 2022-06-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0015_auto_20220629_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_cms_integration.encuesta'),
        ),
    ]
