# Generated by Django 3.2.13 on 2022-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0017_auto_20220705_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langpoll',
            name='economy',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
