# Generated by Django 3.2.13 on 2022-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0018_alter_langpoll_economy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langpoll',
            name='care',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='langpoll',
            name='embedding',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='langpoll',
            name='ethics',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='langpoll',
            name='law',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='langpoll',
            name='technology',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
