# Generated by Django 3.2.13 on 2022-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0019_auto_20220706_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangPoll_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=400)),
                ('choice', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
