# Generated by Django 3.2.13 on 2022-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0020_langpoll_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langpoll_answer',
            name='choice',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
