# Generated by Django 3.2.13 on 2022-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0021_alter_langpoll_answer_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='langpoll_answer',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
