# Generated by Django 3.2.13 on 2022-07-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0022_langpoll_answer_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langpoll_answer',
            name='skipped',
        ),
    ]
