# Generated by Django 3.2.13 on 2022-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0023_remove_langpoll_answer_skipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('setting', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
