# Generated by Django 3.2.13 on 2022-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0024_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkuPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.CharField(blank=True, max_length=400)),
                ('care', models.CharField(blank=True, max_length=400)),
                ('technology', models.CharField(blank=True, max_length=400)),
                ('embedding', models.CharField(blank=True, max_length=400)),
                ('law', models.CharField(blank=True, max_length=400)),
                ('ethics', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AkuPoll_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=400)),
                ('choice', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AmbuPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.CharField(blank=True, max_length=400)),
                ('care', models.CharField(blank=True, max_length=400)),
                ('technology', models.CharField(blank=True, max_length=400)),
                ('embedding', models.CharField(blank=True, max_length=400)),
                ('law', models.CharField(blank=True, max_length=400)),
                ('ethics', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AmbuPoll_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=400)),
                ('choice', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
