# Generated by Django 3.2.13 on 2022-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0025_akupoll_akupoll_answer_ambupoll_ambupoll_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('names', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='langpoll_answer',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
