# Generated by Django 3.2.13 on 2022-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0027_rolesaku_rolesambu_roleslang'),
    ]

    operations = [
        migrations.AddField(
            model_name='langpoll_answer',
            name='skipped_id',
            field=models.IntegerField(default=0),
        ),
    ]
