# Generated by Django 3.2.13 on 2022-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0028_langpoll_answer_skipped_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesaku',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolesambu',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleslang',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
