# Generated by Django 3.2.13 on 2022-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0029_auto_20220801_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='akupoll_answer',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='akupoll_answer',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='akupoll_answer',
            name='skipped_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambupoll_answer',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ambupoll_answer',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambupoll_answer',
            name='skipped_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='langpoll_answer',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
