# Generated by Django 3.2.13 on 2022-09-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0031_auto_20220811_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
