# Generated by Django 3.2.13 on 2022-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0034_workshop_workshop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
