# Generated by Django 3.2.13 on 2022-11-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0035_alter_workshop_workshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='akupoll_answer',
            name='comment_unless',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ambupoll_answer',
            name='comment_unless',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='langpoll_answer',
            name='comment_unless',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
