# Generated by Django 3.2.13 on 2022-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0036_auto_20221101_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='session_id',
            field=models.CharField(max_length=10),
        ),
    ]
