# Generated by Django 3.2.13 on 2022-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0038_auto_20221104_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkuMouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField(default=0)),
                ('economy', models.CharField(blank=True, max_length=400)),
                ('care', models.CharField(blank=True, max_length=400)),
                ('technology', models.CharField(blank=True, max_length=400)),
                ('embedding', models.CharField(blank=True, max_length=400)),
                ('law', models.CharField(blank=True, max_length=400)),
                ('ethics', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AmbuMouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField(default=0)),
                ('economy', models.CharField(blank=True, max_length=400)),
                ('care', models.CharField(blank=True, max_length=400)),
                ('technology', models.CharField(blank=True, max_length=400)),
                ('embedding', models.CharField(blank=True, max_length=400)),
                ('law', models.CharField(blank=True, max_length=400)),
                ('ethics', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
