# Generated by Django 3.2.13 on 2022-12-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0039_akumouse_ambumouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='session_id',
            new_name='workshop_id',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='session_id',
            new_name='workshop_id',
        ),
    ]
