# Generated by Django 3.2.13 on 2022-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0040_auto_20221209_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akupoll_answer',
            old_name='skipped_id',
            new_name='ques_id',
        ),
        migrations.RenameField(
            model_name='ambupoll_answer',
            old_name='skipped_id',
            new_name='ques_id',
        ),
        migrations.RenameField(
            model_name='langpoll_answer',
            old_name='skipped_id',
            new_name='ques_id',
        ),
    ]
