# Generated by Django 3.2.13 on 2022-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0041_auto_20221209_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='akupoll_answer',
            name='workshop_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambupoll_answer',
            name='workshop_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='langpoll_answer',
            name='workshop_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
