# Generated by Django 3.2.13 on 2022-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0042_auto_20221209_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='robot_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
