# Generated by Django 3.2.13 on 2023-01-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0043_setting_robot_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
