# Generated by Django 3.2.13 on 2023-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0044_auto_20230113_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akumouse',
            name='care',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='akumouse',
            name='economy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='akumouse',
            name='embedding',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='akumouse',
            name='ethics',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='akumouse',
            name='law',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='akumouse',
            name='technology',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='care',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='economy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='embedding',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='ethics',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='law',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ambumouse',
            name='technology',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='care',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='economy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='embedding',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='ethics',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='law',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='langmouse',
            name='technology',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
