# Generated by Django 3.2.13 on 2023-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0045_auto_20230220_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role_id',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
